[package]
authors = ["\"tom\" <\"tom.meyer89@gmail.com\">"]
edition = "2018"
name = "embedded_rust_hardware_init"
version = "0.1.0"

[lib]
proc-macro = true

[dependencies]
project-root = "0.2.2"
quote = "1.0.7"
syn = {version = "1.0.38", features = ["full"]}
yaml-rust = "0.4"
