name: Rust on ARM

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - thumbv7m-none-eabi
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
       # toolchain: stable
       target: ${{ matrix.target }}
       # override: true
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
